apiVersion: batch/v1
kind: Job
metadata:
  name: train-vae-job-22r-dorpm-mbmot
  namespace: aoi-lab-scratch

spec:
  template:
    spec:
      containers:
      - name: container
        image: gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python
        command: ["/opt/conda/bin/python"]
        args: ["/volume/code/MMVAE_playground/train.py",
          "--lr", "0.0005", "--max_epochs","1000","--n_dim_hidden","64","--n_dim_latent","24","--batch_size","32", "--train_set_ratio", "0.9",
          "--session_name", "linear_h64_l24_e1000_cv_poi_22R_DORpm_MBmot", "--data_path", "/volume/mydata/SSA", "--save_path", "/volume/code/MMVAE_playground/results",
          "--read_sessions", "22R_D2_SFO_MidBrain_g0_imec0_data", "22R_D2_SFO_MidBrain_g0_imec1_data",
          "--region1", "DORpm", "--region2", "MBmot"]
        resources:
            limits:
              nvidia.com/gpu: "1"
              memory: "12Gi"
              cpu: "2"
            requests:
              memory: "12Gi"
              cpu: "2"
        volumeMounts:
        - mountPath: /volume
          name: benjie-p001
      volumes:
          - name: benjie-p001
            persistentVolumeClaim:
              claimName: benjie-p001
      restartPolicy: OnFailure
          
