apiVersion: v1
kind: Pod
metadata:
  name: ssa-torch-debug
  namespace: aoi-lab-scratch
spec:
  containers:
  - name: container
    image: gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python
    resources:
      limits:
        nvidia.com/gpu: "1"
        memory: "12Gi"
        cpu: "2"
      requests:
        memory: "12Gi"
        cpu: "2"
    volumeMounts:
    - mountPath: /volume
      name: benjie-p001
  volumes:
    - name: benjie-p001
      persistentVolumeClaim:
        claimName: benjie-p001
